name: Test environment deployment

on:
  push:
    branches: ["test"]
    paths:
      - "public/**"
      - "src/**"
  pull_request:
    branches: ["test"]
    paths:
      - "public/**"
      - "src/**"

jobs:
  Build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: datnguyen10102004/frontend:test-${{ github.sha }}

  Update-manifest:
    runs-on: ubuntu-latest
    needs: Build-image
    if: ${{ success() }}
    steps:
      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: NT114-SpecializedProject/infrastructures
          ref: "main"
          token: ${{ secrets.GIT_TOKEN }}
      - name: Update frontend manifest
        run: |
          git config --global user.email "datnguyen101004@gmail.com"
          git config --global user.name "datnguyen10102004"
          sed -i "s#datnguyen10102004/frontend:[^[:space:]]*#datnguyen10102004/frontend:test-${{ github.sha }}#g" ./test/frontend/frontend-deploy.yaml
          git add ./test/frontend/frontend-deploy.yaml
          git commit -m "Update frontend version to test-${{ github.sha }} in test environment"
          git push origin test
