name: Staging environment deployment

on:
  push:
    branches: ["staging"]
    paths:
      - "public/**"
      - "src/**"

jobs:
  Build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: continue3010/frontend:staged-${{ github.sha }}

  Update-manifest:
    runs-on: ubuntu-latest
    needs: Build-image
    if: ${{ success() }}
    steps:
      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: NT114-SpecializedProject/infrastructures
          ref: "main"
          token: ${{ secrets.GH_TOKEN }}
      - name: Update frontend manifest
        run: |
          git config --global user.email "dinhquangdaklak2003@gmail.com"
          git config --global user.name "Continue3010"
          sed -i "s#continue3010/frontend:[^[:space:]]*#continue3010/frontend:staged-${{ github.sha }}#g" ./staging/frontend/frontend-deploy.yaml
          git add ./staging/frontend/frontend-deploy.yaml
          git commit -m "Update frontend version to staged-${{ github.sha }} in staging environment"
          git push origin main
